obj-y += armadillo_iotg_std_addon.o

obj-y += addon_atmark_techno_wi_sun.o \
	 addon_atmark_techno_wi_sun_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_wi_sun_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_wi_sun_x1_intf1.dtb.o

obj-y += addon_atmark_techno_en_ocean.o \
	 addon_atmark_techno_en_ocean_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_en_ocean_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_en_ocean_x1_intf1.dtb.o

obj-y += addon_atmark_techno_serial.o \
	 addon_atmark_techno_serial_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_serial_iotg_g3_intf1_rs485.dtb.o \
	 addon_atmark_techno_serial_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_serial_iotg_g3_intf2_rs485.dtb.o \
	 addon_atmark_techno_serial_x1_intf1.dtb.o \
	 addon_atmark_techno_serial_x1_intf1_rs485.dtb.o

obj-y += addon_atmark_techno_didoad.o \
	 addon_atmark_techno_didoad_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_didoad_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_didoad_x1_intf1.dtb.o

obj-y += addon_atmark_techno_rn4020.o \
	 addon_atmark_techno_rn4020_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_rn4020_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_rn4020_x1_intf1.dtb.o

obj-y += addon_atmark_techno_rs232c.o \
	 addon_atmark_techno_rs232c_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_rs232c_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_rs232c_x1_intf1.dtb.o

obj-y += addon_atmark_techno_rs485.o \
	 addon_atmark_techno_rs485_iotg_g3_intf1.dtb.o \
	 addon_atmark_techno_rs485_iotg_g3_intf2.dtb.o \
	 addon_atmark_techno_rs485_x1_intf1.dtb.o

obj-y += addon_atmark_techno_sd.o \
	 addon_atmark_techno_sd_x1_intf1.dtb.o

obj-y += addon_satori_wireless.o \
	 addon_satori_wireless_iotg_g3_intf1.dtb.o \
	 addon_satori_wireless_iotg_g3_intf2.dtb.o \
	 addon_satori_wireless_x1_intf1.dtb.o

obj-y += addon_advaly_usblan.o \
	 addon_advaly_usblan_iotg_g3_intf1.dtb.o \
	 addon_advaly_usblan_iotg_g3_intf2.dtb.o \
	 addon_advaly_usblan_x1_intf1.dtb.o
